# Generated by Django 4.0.2 on 2022-04-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=30)),
                ('Product', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=30)),
                ('PriceEach', models.CharField(max_length=30)),
                ('OrderDate', models.CharField(max_length=30)),
                ('PurchaseAddress', models.CharField(max_length=30)),
            ],
        ),
    ]
