# Generated by Django 4.0.2 on 2022-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_salesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
