# Generated by Django 4.0.2 on 2022-06-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='datemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datemonth', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
            ],
        ),
    ]
